version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8000:80'
    depends_on:
      - alpha
      - one
#      - zero
  alpha:
    build:
      dockerfile: Dockerfile.dev
      context: ./team-alpha
  one:
    build:
      dockerfile: Dockerfile.dev
      context: ./team-one
#  zero:
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./team-zero
#    ports:
#      - '9000:9000'
