version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8000:80'
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - alpha
      - one
  alpha:
    build:
      dockerfile: Dockerfile.dev
      context: ./team-alpha
  one:
    build:
      dockerfile: Dockerfile.dev
      context: ./team-one
    ports:
      - '9001:9001'
  home:
    build:
      dockerfile: Dockerfile.dev
      context: ./team-home
